# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-15 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LodgeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodge_name', models.CharField(max_length=255)),
                ('lodge_address', models.CharField(max_length=255)),
                ('lodge_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RoomDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=3)),
                ('room_type', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('lodge_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glodge.LodgeDetail')),
            ],
        ),
    ]
